### ISSUE TITLE
Performance / Results

### ISSUE THREAD

**Issue by bsense-rius** [ajayarunachalam/Deep_XF#1]
That's an impressive work!

I was just wondering if you had the chance to check its performance against SARIMAX or alike forecasting algos.

Thank you again!

**Comment by ajayarunachalam** [comment]
Hi, Thanks for your appreciation. I would have loved to check the performance with other forecasting algorithms, but unfortunately due to my busy timeline couldn't work on it any further. As soon as I manage to work on it, I will keep this noted to validate the performances & comparison with alike algorithms.
